from pathlib import Path
from html import escape
resume='output/pdf/Mike-Schnall-Resume-A4.pdf'
linkedin='https://www.linkedin.com/in/mike-mordechai-schnall/'
def link(url,text,cls=''):
 return f'<a class="{cls}" href="{url}" target="_blank" rel="noopener">{text} ↗</a>'
html='''<!doctype html><html lang="en" data-theme="midnight"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Mike Schnall | Senior Solutions Engineer</title><meta name="description" content="Mike Schnall: enterprise integrations, API optimization, and software engineering in New York City."><link rel="icon" href="img/profile.ico"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/redesign-base.css"><link rel="stylesheet" href="css/redesign.css?v=20260906-share-page"><script src="js/redesign.js?v=20260906-share-page" defer></script></head><body><a class="skip" href="#main">Skip to content</a>
<nav id="navbar" aria-label="Main navigation"><div class="header-icons original-icons" aria-label="Profile links"><a href="https://www.linkedin.com/in/mike-mordechai-schnall/" target="_blank" rel="noopener" aria-label="LinkedIn" title="LinkedIn"><img src="img/linkedin.png" alt="LinkedIn" width="36" height="36"></a><a href="https://github.com/mordes89" target="_blank" rel="noopener" aria-label="GitHub" title="GitHub"><img src="img/gh2.png" alt="GitHub" width="36" height="36"></a><a href="output/pdf/Mike-Schnall-Resume-A4.pdf" target="_blank" rel="noopener" aria-label="Resume" title="Resume"><img src="img/cv.png" alt="Resume" width="36" height="36"></a></div><a class="nav-brand" href="#hero"><span class="brand-name">Mike Schnall</span></a><button class="nav-toggle" id="navToggle" aria-label="Toggle menu" aria-expanded="false" aria-controls="navLinks">Menu +</button><ul class="nav-links" id="navLinks"><li><a href="#about" class="nav-link">About</a></li><li><a href="#experience" class="nav-link">Experience</a></li><li><a href="#skills" class="nav-link">Expertise</a></li><li><a href="#contact" class="nav-link">Contact</a></li><li>RESUMENAV</li></ul></nav>
<main id="main"><section id="hero"><div class="hero-bg"><img src="img/photo-04.jpg" alt="" class="hero-img" fetchpriority="high"><img src="img/photo-01.jpg" alt="" class="hero-img hero-img-next" decoding="async"><div class="hero-overlay"></div></div><div class="hero-content"><p class="hero-eyebrow">New York City · Senior Solutions Engineer</p><h1 class="hero-title" aria-label="Mike Schnall">Mike Schnall</h1><p class="hero-tagline">Engineering with<br><em>the user in mind.</em></p><p class="hero-subtitle">I connect complex systems, solve integration challenges,<br>and help people get more from their technology.</p><div class="hero-cta"><a href="#experience" class="btn btn-primary">Explore my work ↓</a>RESUMEBUTTON</div></div><div class="hero-bottom"><span>Currently at <strong>Informed.IQ</strong></span><a href="#about">Meet Mike ↓</a><span>Software · Systems · People</span></div></section>
<section id="about" class="section"><div class="section-inner about-grid"><div class="about-portrait reveal"><div class="portrait-frame"><img src="img/profile-linkedin.jpg" alt="Mike Schnall" loading="lazy"><div class="portrait-accent"></div></div><p class="portrait-label">Engineer. Problem solver.</p></div><div class="reveal"><p class="section-eyebrow">01 / About</p><h2 class="section-heading">Good engineering starts with <em>understanding.</em></h2><p class="lead">I’m a Senior Solutions Engineer at Informed.IQ, helping enterprise clients integrate machine learning verification products into their systems.</p><p class="about-bio">My background spans military service, luxury travel operations, and software engineering. My move into tech began with a database solution that eliminated manual data entry. Seeing that impact sparked a passion for programming and led me through App Academy into enterprise SaaS.</p><p class="about-bio">Today, I combine my economics background with technical troubleshooting, data analysis, and cross-functional leadership. I work closely with clients throughout the full integration process, from understanding their needs and defining requirements to implementation and ongoing optimization, helping them get lasting value from the platform.</p><div class="social-row original-icons"><a href="https://www.linkedin.com/in/mike-mordechai-schnall/" target="_blank" rel="noopener" aria-label="LinkedIn" title="LinkedIn"><img src="img/linkedin.png" alt="LinkedIn" width="48" height="48"></a><a href="https://github.com/mordes89" target="_blank" rel="noopener" aria-label="GitHub" title="GitHub"><img src="img/gh2.png" alt="GitHub" width="48" height="48"></a><a href="output/pdf/Mike-Schnall-Resume-A4.pdf" target="_blank" rel="noopener" aria-label="Resume" title="Resume"><img src="img/cv.png" alt="Resume" width="48" height="48"></a></div></div></div></section>
<section id="experience" class="section section-alt"><div class="section-inner"><div class="section-top reveal"><div><p class="section-eyebrow">02 / Experience</p><h2 class="section-heading">From integration<br>to <em>impact.</em></h2></div><p>Practical solutions, built with an understanding of the technology and the people using it.</p></div>
<article class="career-row reveal"><div><span class="current">Current role</span><p class="date">April 2022 — Present</p></div><div><h3>Senior Solutions Engineer</h3><p class="company">Informed.IQ</p><p>I guide enterprise clients from the sales cycle through technical onboarding and active use of the platform. My role combines hands-on engineering with technical advocacy.</p><ul><li>Gather and document integration requirements, diagnose complex issues, and identify root causes before escalation.</li><li>Translate technical concepts for nontechnical stakeholders and act as a responsive client partner.</li><li>Develop utility scripts to streamline data collection and analyze system activity.</li><li>Use customer analytics to uncover integration gaps, optimize partner APIs, and improve platform efficiency.</li><li>Partner with engineering, product, and customer success to bring client feedback into product planning.</li><li>Create documentation and training materials that help clients use the platform independently.</li></ul><div class="outcome"><strong>300,000+</strong><span>lines of legacy code eliminated through architectural methodologies I implemented.</span></div></div></article>
<article class="career-row reveal"><div><p class="date">May 2015 — June 2021</p></div><div><h3>Database Manager and Bookkeeper</h3><p class="company">Get PEYD, LLC · Inwood, NY</p><p>Created and maintained the company database, automated data collection and financial reporting, and built custom reports for marketing campaigns. Trained and supervised new hires as they joined the team.</p><div class="outcome"><strong>40%+</strong><span>reduction in manual labor through data collection and financial reporting automation.</span></div></div></article>
<details class="earlier reveal"><summary>Earlier experience <span>Operations, service &amp; leadership</span></summary>EARLIER</details></div></section>
<section id="skills" class="section"><div class="section-inner"><p class="section-eyebrow reveal">03 / Expertise</p><h2 class="section-heading reveal">Across the stack.<br><em>Close to the problem.</em></h2><div class="expertise-grid">SKILLS</div></div></section>
<section id="education" class="section section-alt"><div class="section-inner"><p class="section-eyebrow reveal">04 / Education &amp; recognition</p><h2 class="section-heading reveal">Software meets <em>business.</em></h2><div class="education-grid"><article class="reveal"><h3>App Academy</h3><p class="company">Full Stack Web Development Bootcamp</p><p class="date">June — October 2021</p><p>Immersive training in full stack development, including JavaScript, React, Redux, Ruby on Rails, Python, Node.js, SQL, and MongoDB.</p></article><article class="reveal"><h3>Queens College, CUNY</h3><p class="company">BA in Economics</p><p class="date">2016 — 2020</p><p>Graduated magna cum laude with a 3.878 GPA while working full time and attending school full time. Member of the National Society of Collegiate Scholars.</p></article></div><p class="languages reveal"><span>Languages</span> English &amp; Hebrew · Fluent</p></div></section>
<section id="recommendations" class="section"><div class="section-inner"><p class="section-eyebrow reveal">05 / Working together</p><h2 class="section-heading reveal">In my colleagues’ <em>words.</em></h2><div class="quotes"><figure class="reveal"><blockquote>“Mike is a hard worker, a strong collaborator, and a kind soul.”</blockquote><figcaption>Edward Marshall<span>App Academy teammate · October 2021</span></figcaption></figure><figure class="reveal"><blockquote>“He was critical to the frontend styling that allowed our application to properly display songs in leadsheet musical format.”</blockquote><figcaption>Evan Czako<span>App Academy teammate · October 2021</span></figcaption></figure></div>RECOMMENDATIONS</div></section>
<section id="contact" class="section contact-banner"><img src="img/photo-01.jpg" alt="" loading="lazy"><div class="contact-overlay"></div><div class="section-inner contact-content reveal"><p class="section-eyebrow">06 / Get in touch</p><h2>Let’s build something<br><em>that works.</em></h2><p>Have a technical challenge, an opportunity,<br>or a conversation in mind? Let’s connect.</p><a class="email" href="mailto:MMSchnall@gmail.com">MMSchnall@gmail.com ↗</a><div class="social-row original-icons"><a href="https://www.linkedin.com/in/mike-mordechai-schnall/" target="_blank" rel="noopener" aria-label="LinkedIn" title="LinkedIn"><img src="img/linkedin.png" alt="LinkedIn" width="48" height="48"></a><a href="https://github.com/mordes89" target="_blank" rel="noopener" aria-label="GitHub" title="GitHub"><img src="img/gh2.png" alt="GitHub" width="48" height="48"></a><a href="output/pdf/Mike-Schnall-Resume-A4.pdf" target="_blank" rel="noopener" aria-label="Resume" title="Resume"><img src="img/cv.png" alt="Resume" width="48" height="48"></a></div></div></section>
<section id="archive" class="section"><div class="section-inner"><div class="section-top reveal"><div><p class="section-eyebrow">From the archive / App Academy</p><h2 class="archive-title">Where it <em>started.</em></h2></div><p>My first game, written at App Academy. A small, slightly ridiculous reminder that everyone starts somewhere.</p></div><div class="archive-grid">PROJECTS</div></div></section>
<section id="share" class="section share-qr"><div class="section-inner"><div class="contact-download"><p class="section-eyebrow">Save my contact details</p><h2 class="archive-title">Download my contact info<br><em>&amp; save as contact.</em></h2><p>Scan this QR code or click below to download my contact card.<br>Open the file, then save it to your contacts.</p><a href="mike.vcf" download="Mike-Schnall.vcf" aria-label="Download Mike Schnall contact card"><img src="output/business-card/Mike-Schnall-New-Contact-QR.png" width="320" height="320" alt="Contact QR: scan to download Mike Schnall contact card" loading="lazy"></a><a class="btn btn-outline" href="mike.vcf" download="Mike-Schnall.vcf">Download my contact info</a><div class="contact-details"><p><strong>Mike Schnall</strong><br>Senior Solutions Engineer · Informed.IQ</p><p><a href="tel:+16823651263">682-365-1263</a><br><a href="mailto:MMSchnall@gmail.com">MMSchnall@gmail.com</a></p><p><a href="https://www.linkedin.com/in/mike-mordechai-schnall/" target="_blank" rel="noopener">LinkedIn</a> · <a href="https://mordes89.github.io/Mike-Schnall-portfolio/" target="_blank" rel="noopener">Portfolio website</a></p></div></div><div class="portfolio-share"><p class="section-eyebrow">QR code to my portfolio website</p><h2 class="archive-title">Share my portfolio<br><em>with others.</em></h2><p>Scan this QR code to open my portfolio website.<br>Click the image to save the QR code and share it with someone.</p><a href="output/business-card/Mike-Schnall-New-Portfolio-QR.png" download="Mike-Schnall-Portfolio-QR.png" aria-label="Save the QR code to Mike Schnall portfolio website"><img src="output/business-card/Mike-Schnall-New-Portfolio-QR.png" width="320" height="320" alt="Website QR: scan to open Mike Schnall portfolio" loading="lazy"></a><div class="page-share"><button type="button" class="btn btn-outline" id="sharePage"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4M8.6 13.5l6.8 4"/></svg>Share this page</button><p id="shareStatus" role="status" aria-live="polite"></p><p id="shareFallback" hidden><a href="https://mordes89.github.io/Mike-Schnall-portfolio/">https://mordes89.github.io/Mike-Schnall-portfolio/</a></p></div></div></div></section></main><footer id="footer"><a class="nav-brand" href="#hero">Mike Schnall<span class="gold">.</span></a><span>Senior Solutions Engineer · New York City</span><a href="#hero">Back to top ↑</a></footer></body></html>'''
earlier=[('March 2014 — January 2015','Delta Towing','Roadside Assistance Operative · Dallas, TX','Provided emergency roadside assistance with an incident-free record, including recovering a truck from a 25-foot ditch without additional damage.'),('October 2012 — February 2014','Discount Bank','Security Officer · Jerusalem','Led a team securing the central branch with an incident-free record and implemented protocols to reduce theft risk.'),('September 2011 — August 2012','FDNY Fire Zone','Sales Representative · New York, NY','Managed inventory, improved tracking, developed sales strategies, and coordinated with the supply chain team.'),('August 2010 — July 2011','Hapoel Jerusalem Basketball Club','Sports Equipment Manager · Jerusalem','Improved inventory systems, reducing misplacement and theft by more than 70%. Managed equipment logistics for international travel and anticipated team needs.'),('July 2007 — July 2010','Israel Defense Forces','Infantry Soldier · Israel','Led a team, coordinated information, and built an inclusive unit culture. Awarded Exemplary Infantryman in advanced training; highest rank held: Staff Sergeant.')]
earlier_bullets={
'Delta Towing':[
'Provided emergency assistance to stranded roadsters with a 100% incident-free record.',
'Rescued a truck from a 25ft ditch with no additional damage to the vehicle, enabling the client to drive home from the scene.'
],
'Discount Bank':[
'Led a team of officers tasked with the security of the Central Branch with an incident free record.',
'Implemented security protocols that decreased the likelihood of theft by >50%.'
],
'FDNY Fire Zone':[
'Took charge of store inventory and made necessary updates to the system for greater accuracy and more efficient tracking.',
'Implemented strategies that improved customer traffic and increased sales revenues.',
'Recognized weaknesses, and addressed them to increase closed-sales by >200%.',
'Coordinated with the Supply Chain Team to facilitate a more efficient operation to move merchandise.'
],
'Hapoel Jerusalem Basketball Club':[
'Optimized the inventory-system for holding precise amounts, resulting in >70% less misplacement and theft.',
'Administered equipment logistics for international travel, providing a superior experience for players and staff while abroad.',
'Coordinated with jobsite superintendents and other departments to ensure equipment is ready when needed to meet team needs.',
'Initiated a system that anticipated future needs of players and staff, which decreased frantic last-minute demands.'
],
'Israel Defense Forces':[
'Led a team of soldiers in covert military operations with a >90% record objective completion.',
'Managed classified information regarding covert operations, ensuring every soldier had the information needed to fulfil their objectives.',
'Awarded Exemplary-infantryman in advanced training. Highest rank held: Staff Sergeant.',
'Adopted an inclusive-culture that fostered positive chemistry within the unit, improving morale and team performance.'
]}
earlier_html=''.join(f'<article class="career-row"><p class="date">{d}</p><div><h3>{c}</h3><p class="company">{r}</p><ul>'+''.join('<li>'+escape(b)+'</li>' for b in earlier_bullets[c])+'</ul></div></article>' for d,c,r,t in earlier)

skills=[('Integration & architecture','Connect enterprise platforms, diagnose complex issues, and translate client needs into implementation plans.','API integrations · AWS · Heroku · Technical support · Client onboarding'),('Software & automation','Build tools and applications that simplify work, from utility scripts to interactive web experiences.','Full-stack development · Python · JavaScript · Ruby · Ruby on Rails · Node.js · Express.js · Git · WSL'),('Interfaces & interaction','Bring application logic and user experience together in responsive web interfaces.','React · Redux · HTML · CSS · Sass · Webpack · jQuery'),('Data & analysis','Use system activity and client data to find gaps and improve reporting and technical decisions.','SQL · PostgreSQL · SQLite3 · MongoDB · Mongoose · Data analysis'),('People & delivery','Connect teams, share knowledge, and guide clients and new colleagues through technical change.','Leadership · Management · Project management · New hire training · Training · Team building · Team leadership'),('Business & operations','Bring an economics and operations perspective to technical decisions and process improvement.','Strategic planning · Sales · Customer service · Microsoft Office · Security')]
skills_html=''.join(f'<article class="reveal"><span class="skill-number">0{i+1}</span><h3>{t}</h3><p>{d}</p><p class="tool-list">{s}</p></article>' for i,(t,d,s) in enumerate(skills))
projects=[('img/ehps-pic.png','Exploding Hot Potato Soccer','The first game I ever wrote while learning to be a software engineer. It combines soccer, hot potato, and a ball that explodes at unpredictable intervals. Subtle? No. A little rough around the edges? Absolutely. But it has charm, and I still have a soft spot for it. (Voiceover in the game by yours truly.)','JavaScript · CSS · Sprite animation','https://github.com/mordes89/EXPLODING-HOT-POTATO-SOCCER-')]
projects_html=''.join(f'<article class="archive-project reveal"><img src="{im}" alt="{t} screenshot" loading="lazy"><div><h3>{t}</h3><p>{d}</p><p class="tool-list">{s}</p>{link(url,"Explore the source")}</div></article>' for im,t,d,s,url in projects)
subs={'RESUMENAV':link(resume,'Resume','nav-link'),'RESUMEBUTTON':link(resume,'View resume','btn btn-outline'),'RESUME':link(resume,'Resume'),'LINKEDIN':link(linkedin,'LinkedIn'),'GITHUB':link('https://github.com/mordes89','GitHub'),'RECOMMENDATIONS':link(linkedin+'details/recommendations/','Read more on LinkedIn'),'THEMES':''.join(f'<button class="theme-btn" data-theme="{t}" aria-label="{label} theme" aria-pressed="{str(i==0).lower()}" title="{label}" style="background:{color}"></button>' for i,(t,label,color) in enumerate([('midnight','Midnight','#303852'),('ivory','Ivory','#e5dcc1'),('jazz','Amber','#b77836'),('crimson','Crimson','#8e3454'),('emerald','Emerald','#397555')])),'EARLIER':earlier_html,'SKILLS':skills_html,'PROJECTS':projects_html}
for key,val in subs.items():html=html.replace(key,val)
Path('index.html').write_text(html,encoding='utf-8')
